services:
  moodle:
    image: moodlehq/moodle-php-apache:latest
    ports:
      - "8080:80"
    environment:
      - MOODLE_DBTYPE=mysqli
      - MOODLE_DBHOST=db
      - MOODLE_DBNAME=moodle
      - MOODLE_DBUSER=moodleuser
      - MOODLE_DBPASS=moodlepass
      - MOODLE_WWWROOT=http://localhost:8080
    depends_on:
      - db
    volumes:
      # Mount your extracted Moodle code into the container.
      - ./moodle:/var/www/html
      # Persist Moodle data outside the container.
      - moodledata:/var/www/moodledata

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  moodledata:
  db_data:
